//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCake
    {
        public int CakeID { get; set; }
        public string CakeName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Grown { get; set; }
        public Nullable<bool> Kids { get; set; }
    }
}
