//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCakeList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCakeList()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int CakeListID { get; set; }
        public Nullable<int> LjubavnoGnezdo { get; set; }
        public Nullable<int> Lincer { get; set; }
        public Nullable<int> Cheese { get; set; }
        public Nullable<int> Dobos { get; set; }
        public Nullable<int> Bomba { get; set; }
        public Nullable<int> Kinder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
