//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int CakeID { get; set; }
        public double TotalPrice { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int NumberOfCakes { get; set; }
        public int UserID { get; set; }
        public int CakeListID { get; set; }
    
        public virtual tblCakeList tblCakeList { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
